### ISSUE TITLE
No pom. 'tomcat_oscar' failed to build

### ISSUE THREAD

**Issue by tyrannotorus** [dermatologist/oscar-latest-docker#3]
This is what I get running `./install.sh` on Linux Mint 19.2 Cinnamon

> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 0.112 s
> [INFO] Finished at: 2019-11-21T03:11:55+00:00
> [INFO] Final Memory: 5M/150M
> [INFO] ------------------------------------------------------------------------
> [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/oscar). Please verify you invoked Maven from the correct directory. -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
> ERROR: Service 'tomcat_oscar' failed to build: The command '/bin/sh -c /home/build.sh' returned a non-zero code: 1
> OSCAR is set up at http://localhost:8091/oscar_mcmaster
> You may have to restart the container http://localhost:8091/  (oscar/oscar)
> Errors if any are more likely to be in the database import!
> Thank You..
> Visit our website for more info: http://nuchange.ca

**Comment by dermatologist** [comment]
Hi @tyrannotorus 

install.sh starts by cloning the OSCAR repo into the root folder of this repo. Can you confirm that you have an oscar folder inside the root folder? Did you see any output from git clone?

You can manually clone as below: 

```
git clone --depth 1 --single-branch --branch feature/Container-1 https://github.com/E-Health/oscar.git
```

**Comment by tyrannotorus** [comment]
I guess the instructions ...

> Just clone this repo and ./install.sh

... may not be enough for a first time user who's unfamiliar. I downloaded the zip (which I thought was as good as cloning), extracted it, and ran ./install.sh, expecting it to work :)

It looks like I'm up and running now, by running the script you posted to clone oscar into `/home/oscar/`, then extracting the zip from this repo into `/home/oscar/`, and then running `install.sh`

Just expanding the install instructions in README.md would be a help.

Thanks!

**Comment by dermatologist** [comment]
Install.sh does the cloning. I am not sure why it did not happen in your case. Anyways nice to know that it worked. Closing this now.
